
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-php-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://bajram:Vfbstuttgart@db:5432/restaurant
      - MONGODB_URL=mongodb://Bajram:Vfbstuttgart@mongodb:27017/restaurant_mongo_db?authSource=admin
    ports:
      - "8084:80"
    volumes:
      - ./app:/var/www
    depends_on:
      - db
      - mongodb
    networks:
      - app_network

  db:
    image: postgres:16
    container_name: restaurant-postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bajram
      POSTGRES_PASSWORD: Vfbstuttgart
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app_network

  mongodb:
    image: mongo:6.0
    container_name: restaurant-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: Bajram
      MONGO_INITDB_ROOT_PASSWORD: Vfbstuttgart
    volumes:
      - mongodb-data:/data/db
    networks:
      - app_network

volumes:
  postgres-data:
  mongodb-data:

networks:
  app_network:
    driver: bridge



